version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "4306:3306" # primero puerto para acceder desde fuera del contenedor, el otro se conectara por default al 3306 en docker compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      
  wordpress:
    depends_on:
      - db
    image: wordpress:latest #instala wordpress con la ultima version
    volumes:
      - ./src/themes:/var/www/html/wp-content/themes #temas del wordpress
      - ./src/plugins:/var/www/html/wp-content/plugins # para los plugins
      - ./src/uploads:/var/www/html/wp-content/uploads # para el gestor de multimedia

    ports:
      - "8000:80" #por contenedor exterior usamos el 8000 y por interno el 80
    
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      


